name: Laravel application (Mysql)
run-name: Build, Push and Deploy image simple social media
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: "${{ secrets.DOCKER_USER }}/agnes-simple-social-media"
  DOCKER_USER: "${{ secrets.DOCKER_USER }}"
jobs:
  run-mysql-in-docker:
    runs-on: self-hosted
    steps:
      - name: Remove old mysql container (safe)
        continue-on-error: true
        run: docker rm -f mysql || true
      - name: Run MySQL container
        run:  
          docker run -d \
          --name mysql \
          -e MYSQL_ROOT_PASSWORD=password \
          -e MYSQL_DATABASE=social_media \
          -p 3307:3306 \
          mysql:5.7
      - name: List containers
        run: docker ps -a
  build-push-image:
    needs: run-mysql-in-docker
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker image ls
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy-social-media:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: stop old container safely
        run: docker compose down || true
      - name: start container
        run: docker compose up -d
      - name: Cleanup unused docker resources
        run: docker system prune -f
